---
- name: Deploy Dynatrace
  hosts: localhost
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Pip is installed.
      package:
        name: python-pip
        state: present

    - name: Ensure OpenShift client is installed.
      pip:
        name: openshift
        state: present

  tasks:
    - name: Create dynatrace k8s namespace
      k8s:
        name: dynatrace
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy Dynatrace operator
      k8s:
        state: present
        src: ../manifests/dynatrace-oneagent-operator.yaml

    - name: Deploy Dynatrace OneAgent
      k8s:
        state: present
        src: ../manifests/dynatrace-oneagent.yaml
